Task/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Task.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
            
        }
        
        public DbSet<MyTask> Tasks { get; set; }
        
    }
}

Task/Models/IMyTaskRepository.cs
using System.Collections.Generic;

namespace Task.Models
{
    public interface IMyTaskRepository
    {
        IEnumerable<MyTask> AllTasks { get; }
        bool CreateTask(MyTask task);
        MyTask GetTask(int id);
        bool UpdateTask(MyTask task);
        bool DeleteTask(MyTask task);
    }
}

Task/Models/MyTask.cs
using System.ComponentModel.DataAnnotations;

namespace Task.Models
{
    public class MyTask
    {
        public int MyTaskId { get; set; }
        
        [Required(ErrorMessage = "Task name is requires")]
        [StringLength(50)]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Description is required")]
        [StringLength(60)]
        public string Description { get; set; }
    }
}

Task/Models/MyTaskRepository.cs
using System.Collections.Generic;
using System.Linq;

namespace Task.Models
{
    public class MyTaskRepository : IMyTaskRepository
    {
        private readonly AppDbContext _appDbContext;
        public MyTaskRepository(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IEnumerable<MyTask> AllTasks => _appDbContext.Tasks;

        public bool CreateTask(MyTask task)
        {
            _appDbContext.Tasks.Add(task);

            return _appDbContext.SaveChanges() > 0;
        }

        public MyTask GetTask(int id) => _appDbContext.Tasks.FirstOrDefault(t => t.MyTaskId == id);

        public bool UpdateTask(MyTask task)
        {
            _appDbContext.Tasks.Update(task);
            return _appDbContext.SaveChanges() > 0;
        }

        public bool DeleteTask(MyTask task)
        {
            _appDbContext.Tasks.Remove(task);
            return _appDbContext.SaveChanges() > 0;
        }
    }
}

Task/Controllers/MyTaskController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class MyTaskController : Controller
    {

        private readonly IMyTaskRepository _myTaskRepository;

        public MyTaskController(IMyTaskRepository myTaskRepository)
        {
            _myTaskRepository = myTaskRepository;
        }
        
        // GET
        public IActionResult Index()
        {
            IEnumerable<MyTask> myTasks = _myTaskRepository.AllTasks;
            return View(myTasks);
        }
        
        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(MyTask task)
        {
            if (ModelState.IsValid)
            {
                _myTaskRepository.CreateTask(task);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int id)
        {
            MyTask task = _myTaskRepository.GetTask(id);
            return View(task);
        }

        [HttpPost]
        public IActionResult Update(MyTask task)
        {
            if (ModelState.IsValid)
            {
                _myTaskRepository.UpdateTask(task);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Edit");
        }

        
        public IActionResult Delete(int id)
        {
            MyTask task = _myTaskRepository.GetTask(id);
            _myTaskRepository.DeleteTask(task);
            return RedirectToAction("Index");
        }
        
    }
}

Task/Views/Home/Index.cshtml
<h1>Homepage</h1>
<a asp-controller="MyTask" asp-action="Index">Tasks</a>

Task/Views/MyTask/Create.cshtml
@model MyTask
<h1>Add task</h1>
<a asp-controller="MyTask" asp-action="Index">Back</a>


<div style="margin-top: 20px">
    
    <form asp-action="Create" method="post">

        <label asp-for="Name"></label><br/>
        <input asp-for="Name"/><br/>
        <span asp-validation-for="Name" style="color: red"></span><br/>
        
        <label asp-for="Description"></label><br/>
        <textarea asp-for="Description"></textarea><br/>
        <span asp-validation-for="Description" style="color: red"></span><br/><br/>

        <button type="submit">Add</button>

    </form>
    
</div>

Task/Views/MyTask/Edit.cshtml
@model MyTask

<h1>Add task</h1>
<a asp-controller="MyTask" asp-action="Index">Back</a>


<div style="margin-top: 20px">
    
    <form asp-action="Update"  method="post">

        <input asp-for="MyTaskId" value="@Model.MyTaskId" style="display: none;"/>
        
        <label asp-for="Name"></label><br/>
        <input asp-for="Name" value="@Model.Name"/><br/>
        <span asp-validation-for="Name" style="color: red"></span><br/>
        
        <label asp-for="Description"></label><br/>
        <textarea asp-for="Description">@Model.Description</textarea><br/>
        <span asp-validation-for="Description" style="color: red"></span><br/><br/>

        <button type="submit">Update</button>

    </form>
    
</div>

Task/Views/MyTask/Index.cshtml
@model IEnumerable<MyTask>
<h1>Tasks</h1>
<a asp-controller="MyTask" asp-action="Create">Add task</a>

<br/><br/>
<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var task in @Model)
    {
        <tr>
            <td>@task.Name</td>
            <td>@task.Description</td>
            <td>
                <a asp-controller="MyTask" asp-action="Edit" asp-route-id="@task.MyTaskId">Edit</a>
            </td>
            <td>
                <a asp-controller="MyTask" asp-action="Delete" asp-route-id="@task.MyTaskId">Delete</a>
            </td>
        </tr>
    }
</table>

Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Task</title>
</head>
<body>
<div>
    @RenderBody()  
</div>
</body>
</html>